-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Element CASCADE;
DROP TABLE IF EXISTS Clas CASCADE;
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Avatar CASCADE;
DROP TABLE IF EXISTS Item CASCADE;
DROP TABLE IF EXISTS Ownership CASCADE;